# Generated by Django 4.1.3 on 2022-11-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_choice_matchs_question_delete_polls_choice_question"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Matchs",
            new_name="Match",
        ),
    ]
