# Generated by Django 4.1.3 on 2022-11-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_matchs_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="played",
            field=models.BooleanField(default=False),
        ),
    ]
