# Generated by Django 4.1.3 on 2022-11-13 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_match_played"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="poll",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="polls.poll"
            ),
        ),
    ]
