# Generated by Django 4.1.3 on 2022-11-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_matchchoice_questionchoice_question_poll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='played',
        ),
        migrations.AddField(
            model_name='matchchoice',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
