# Generated by Django 4.1.3 on 2022-11-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_matchchoice_questionchoice_question_poll_and_more"),
        ("polls", "0006_question_poll_pronostic"),
    ]

    operations = []
