# Generated by Django 4.1.3 on 2022-11-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_merge_20221114_0003"),
        ("polls", "0008_question_answer"),
    ]

    operations = []
