# Generated by Django 4.1.3 on 2022-11-19 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0009_alter_question_answer_pronostic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=30)),
                ("squad_1", models.CharField(max_length=20)),
                ("squad_2", models.CharField(max_length=20)),
                ("squad_3", models.CharField(max_length=20)),
                ("squad_4", models.CharField(max_length=20)),
                ("rank_1", models.IntegerField(default=-1)),
                ("rank_2", models.IntegerField(default=-1)),
                ("rank_3", models.IntegerField(default=-1)),
                ("rank_4", models.IntegerField(default=-1)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "poll",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.poll",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank_1", models.IntegerField(default=-1)),
                ("rank_2", models.IntegerField(default=-1)),
                ("rank_3", models.IntegerField(default=-1)),
                ("rank_4", models.IntegerField(default=-1)),
                ("points", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
