# Generated by Django 4.1.3 on 2022-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_group_groupchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pointScoreType',
            field=models.CharField(default='EXACT', max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
