# Generated by Django 4.1.3 on 2022-12-01 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_question_pointscoretype_question_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_1', models.CharField(max_length=20)),
                ('squad_2', models.CharField(max_length=20)),
                ('answer', models.CharField(default='None', max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='QualifChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='None', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('qualif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.qualif')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
