# Generated by Django 4.1.3 on 2022-12-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_qualif_qualifchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='choice',
            field=models.CharField(max_length=300),
        ),
    ]
