# Generated by Django 4.1.3 on 2022-12-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_questionchoice_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='diff_score',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='poll',
            name='exact_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='poll',
            name='minority_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='qualif_score',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='poll',
            name='rank_factor_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='poll',
            name='rank_score',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='poll',
            name='win_score',
            field=models.IntegerField(default=2),
        ),
    ]
