# Generated by Django 4.1.3 on 2026-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_poll_diff_score_poll_exact_score_poll_minority_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cote_1',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='match',
            name='cote_2',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='match',
            name='cote_N',
            field=models.FloatField(default=10.0),
        ),
    ]
